# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: action-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    - name: Front-end compilation
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +
    - name: Back-end compilation
      run: |
        cd api
        find . -name "*.js" -exec node --check {} +
        
  gitleaks-scanner:
      runs-on: action-runner
      needs: build
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cleanup stale Gitleaks binaries
        run: rm -f /tmp/gitleaks.tmp
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
      - name: Gitleaks scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1

  trivy-scanner:
      runs-on: action-runner
      needs: gitleaks-scanner
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run Trivy vulnerability scanner in fs mode
          uses: aquasecurity/trivy-action@0.28.0
          with:
            scan-type: "fs"
            format: table
            scan-ref: .
            severity: HIGH,CRITICAL
            ignore-unfixed: true
            # exit-code: 1
          
    
